[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
analyzer = { path = "../analyzer" }
visitor = { path = "../visitor" }
type_info ={ path = "../type_info/" }

biome_js_parser = { workspace = true }
biome_js_syntax = { workspace = true }
biome_rowan = { workspace = true }